name: GitHub Action CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: +lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: ["26", "27", "28"]
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: ^0.7
      - uses: actions/checkout@v3
      - name: +lint
        run: earthly --use-inline-cache +lint --EMACS_VERSION=${{ matrix.emacs_version }}
